// Kept local on purpose: no remote copy, no analytics, no surprises.
window.ROAST_BANK = [
  { category: "first", text: "oh wow. the algorithm found the person your taste keeps trying to uninstall." },
  { category: "first", text: "🚨 ex detected. close the tab before your self-respect starts buffering." },
  { category: "first", text: "you said ‘i’m over it’ with the confidence of a browser reopening the same tab." },
  { category: "first", text: "that face again? your feed has worse boundaries than a group project." },
  { category: "first", text: "spotted: the human pop-up ad you never agreed to see again." },
  { category: "first", text: "congrats, you found the limited edition bad decision collector’s item." },
  { category: "repeat", text: "again? this isn’t scrolling, this is archaeological excavation of poor choices." },
  { category: "repeat", text: "you’re not ‘just curious.’ even incognito mode is judging you." },
  { category: "repeat", text: "second sighting. at this point the tab needs a restraining order." },
  { category: "repeat", text: "you keep revisiting this like the ending will get patched in the next update." },
  { category: "repeat", text: "the algorithm has officially filed a missing-person report for your standards." },
  { category: "repeat", text: "you had one job: scroll past. somehow that was the final boss." },
  { category: "high-confidence", text: "99% match. 100% chance this is not the character development you ordered." },
  { category: "high-confidence", text: "high-confidence hit: your ex, serving the same face with zero new content." },
  { category: "high-confidence", text: "confirmed. that’s the plot twist nobody asked to renew for another season." },
  { category: "high-confidence", text: "radar locked on. your peace has been asked to leave the chat." },
  { category: "high-confidence", text: "face match verified. emotional antivirus strongly recommends closing this window." },
  { category: "high-confidence", text: "it’s definitely them. somewhere, a red flag just got its blue tick." },
  { category: "late-night", text: "late-night ex detection is bold. put the phone down, captain bad ideas." },
  { category: "late-night", text: "after midnight? this isn’t nostalgia, it’s a system vulnerability." },
  { category: "late-night", text: "the witching hour called. it wants its questionable decisions back." },
  { category: "late-night", text: "go to sleep. your frontal lobe has left the group chat for the evening." },
  { category: "late-night", text: "this tab is not closure. it’s just insomnia wearing Wi‑Fi." },
  { category: "any", text: "breaking news: the past remains aggressively underwhelming." },
  { category: "any", text: "your screen time report is going to need a therapist." },
  { category: "any", text: "this is your sign to hydrate, log off, and recover your main-character budget." },
  { category: "any", text: "the face is familiar. the decision to keep looking is the real plot hole." },
  { category: "any", text: "ex detector says: no contact was a policy, not a loading screen." }
];
